### ISSUE TITLE
[Feature]: Compatibility with Ultimate Fertilizer or similar mods

### ISSUE THREAD

**Issue by JZ0125** [Annosz/UIInfoSuite2#509] opened 2024-04-27 15:26 UTC
### Description

With the crop info on, when adding second fertilizer using the Ultimate Fertilizer mod, the game would freeze. If the crop info is turned off first, after adding more fertilizer to a tile, and then turning the crop info back on, it would cause errors in SMAPI console.
I assume this is because the code is designed to handle only one fertilizer. Would it be possible to add compatibility with multiple fertilizer mods like Ultimate Fertilizer by allowing multiple fertilizer info to be displayed? Thanks

**Comment by drewhoener** [comment] 2024-04-27 15:28
Duplicate of #493

**Closed by drewhoener** 2024-04-27 15:28 UTC
Labels: enhancement, triage
