### ISSUE TITLE
[Bug]: scarecrow range misaligned when zoom is changed

### ISSUE THREAD

**Issue by kinumikokuryu** [Annosz/UIInfoSuite2#391] opened 2024-03-20 19:30 UTC
### Game Version

v2.3.0-alpha-2

### Multiplayer

Single Player

### Breaking Bug

Non-Breaking

### Visual Settings

UI Scale: 80%, Zoom: 75%

### Description

when i adjust the game zoom level the range guide get misaligned but is normal at the default zoom
![Screenshot 2024-03-20 122346](https://github.com/Annosz/UIInfoSuite2/assets/123017044/ae02b2b9-effd-4347-a5b0-23f349225b76)
![image_2024-03-20_122859165](https://github.com/Annosz/UIInfoSuite2/assets/123017044/529669e8-e032-40ef-b6ce-466c6dc53991)

**Comment by drewhoener** [comment] 2024-03-20 20:14
Duplicate of #377

**Closed** 2024-03-20 21:24 UTC
Labels: bug, duplicate
