### ISSUE TITLE
[Breaking]: Upgrade copper pan to silver pan result to error  

### ISSUE THREAD

**Issue by toanvkht** [Annosz/UIInfoSuite2#608] opened 2024-10-19 18:26 UTC
### Mod Version

v2.3.4

### Multiplayer

Single Player

### SMAPI Log

https://smapi.io/log/ca308f267469435da29d68e370f587d4

### Description

line 101
[UI Info Suite 2] This mod failed in the Display.RenderedHud event. Technical details:
NullReferenceException: Object reference not set to an instance of an object.
   at UIInfoSuite2.UIElements.ShowToolUpgradeStatus.OnRenderedHud(Object sender, RenderedHudEventArgs e) in C:\Users\Drew\RiderProjects\

I go to clint and proceed to upgrade copper pan to silver pan and immediately the error appears and continue to loop, then it lead to crash

**Comment by drewhoener** [comment] 2024-10-22 16:12
Duplicate of #560, please use the debug build there. Sorry for the inconvenience, most of my time has been going to the rewrite

**Closed** 2024-10-22 16:13 UTC
Labels: bug (breaking), triage
