### ISSUE TITLE
[Visual Bug]: Sprinkler and Scarecrow AoE is showing incorrectly

### ISSUE THREAD

**Issue by travismcgrath** [Annosz/UIInfoSuite2#425] opened 2024-03-23 00:02 UTC
### Mod Version

v2.3.0

### Multiplayer

Multiplayer (Host)

### Visual Settings

Zoom: full zoomed out

### Steps to Reproduce
1. pick up a sprinkler or scarecrow

<img width="576" alt="image" src="https://github.com/Annosz/UIInfoSuite2/assets/33809877/6e260630-f658-450c-bbbb-e98da386521f">

**Comment by drewhoener** [comment] 2024-03-23 04:40
Hi @travismcgrath, are you sure you have the latest version? This should have been fixed by 2.3.0. 
If not, could you please upload your smapi log?

**Comment by travismcgrath** [comment] 2024-03-23 12:47
Oh good call. I'll update and see if that resolves it.

**Comment by strelok144** [comment] 2024-03-24 13:48
I have the same problem on v2.3.0 version.

**Comment by drewhoener** [comment] 2024-03-24 14:46
Hey @travismcgrath @strelok144, I'm not sure what you're experiencing, but I can't reproduce this in my dev world.
![image](https://github.com/Annosz/UIInfoSuite2/assets/6218989/4b8d858b-ab04-4d0c-adb4-1b08977d28bd)

I know you said you were on v2.3.0, but I'm using your scaling settings and the issue just doesn't seem to be there.
Unless you can provide some more detailed reproduction steps, there's not much more I can do about this

**Comment by travismcgrath** [comment] 2024-03-24 14:54
I think the issue I had was fixed by updating to v2.3.0.

Thanks!

**Closed** 2024-03-25 03:39 UTC
Labels: bug (visual), unverified, duplicate
