### ISSUE TITLE
[Bug]: villager map location

### ISSUE THREAD

**Issue by twistyyfern** [Annosz/UIInfoSuite2#392] opened 2024-03-20 19:43 UTC
### Game Version

v2.3.0-alpha-2

### Multiplayer

Multiplayer (Non-Host)

### Breaking Bug

Non-Breaking

### Visual Settings

UI Scale: 100%, Zoom: 100%

### Description

locations for villagers on spring 7 were wrong, with the map saying harvey was at pierres, he was outside behind jodis, jodi was said to be at home, while she was at the service in the back of pierres. untested whether this will happen on other days, if its reverting to just a standard schedule or some other error

**Comment by drewhoener** [comment] 2024-03-24 20:42
Duplicate of #433

**Closed** 2024-03-24 20:42 UTC
Labels: bug (visual), duplicate
