### ISSUE TITLE
Request - Weather icon for Ginger Island

### ISSUE THREAD

**Issue by KarmaCreations** [Annosz/UIInfoSuite2#166] opened 2022-04-20 21:46 UTC
It was nice not having to check the TV for the weather, but now that I've unlocked Ginger Island, I still have to check it every day to know whether or not it's going to rain on the island. Would love having a separate icon for the island weather :)

**Comment by Annosz** [comment] 2022-05-05 15:52
Duplicate of #33, will continue investigation there.

**Closed by Annosz** 2022-05-05 15:52 UTC
