### ISSUE TITLE
[Mobile] Farm map issues

### ISSUE THREAD

**Issue by Melzzip** [Annosz/UIInfoSuite2#327] opened 2023-08-02 17:17 UTC
I'm having problems with the farm map in question. every time I open it, the sprites of the characters do not appear, they only appear on the construction page, I already installed and uninstalled the mod, I installed an old version and nothing. Well I'm a mobile player what do I do??

**Comment by Annosz** [comment] 2024-03-20 07:59
I will close this issue as a duplicate of https://github.com/Annosz/UIInfoSuite2/issues/327. Please revisit that ticket for future updates.

**Closed by Annosz** 2024-03-20 07:59 UTC
