### ISSUE TITLE
Ultimate fertilizer Mod, information reading problem

### ISSUE THREAD

**Issue by mmm4899** [Annosz/UIInfoSuite2#498] opened 2024-04-21 06:52 UTC
### Mod Version

v2.3.2

### Multiplayer

Single Player

### SMAPI Log

https://smapi.io/log/8a6232f84e0e4c4897e8ef4edef46cf0

### Description

Move the mouse to the indoor flowerpot plant.
The plant is sprinkled with two fertilizers (using the "[Ultimate Fertilizer](https://www.nexusmods.com/stardewvalley/mods/21318)" module)

Speculation: The new version of UI2 has added the function of displaying fertilizer spread by crops, but the program can't be understood when it meets two kinds of fertilizer crops, so it outputs red wildly to report an error.

**Comment by drewhoener** [comment] 2024-04-22 22:16
Duplicate of #493

**Closed by drewhoener** 2024-04-22 22:16 UTC
Labels: bug (breaking), triage
