### ISSUE TITLE
[Visual Bug]: Item hover Info breaks on anything other than 100% zoom.

### ISSUE THREAD

**Issue by TheBros13** [Annosz/UIInfoSuite2#404] opened 2024-03-21 00:51 UTC
### Game Version

v2.3.0-alpha-2

### Multiplayer

Single Player

### Visual Settings

UI Scale: 75% UI Zoom: 75%

### Issue
<!---
    the item hover info doesnt appear unless hovering over it in your hotbar if your zoom is not at 100%, and is far from the item if the UI scale is not 100%
---!>

### Steps to Reproduce

(info not appearing) 1. turn ui zoom up/down from 100 
                                 2. enjoy! 
![20240321114808_1](https://github.com/Annosz/UIInfoSuite2/assets/164276816/d0c03f03-61a6-4c10-91b8-f3ada4e4df64)

(info is far from item) 1. turn ui scale up/down from 100
                                   2. enjoy!
![20240321114818_1](https://github.com/Annosz/UIInfoSuite2/assets/164276816/29735c7e-6f13-4818-ae8c-e3aa8aa126d6)

**Comment by drewhoener** [comment] 2024-03-21 00:52
Duplicate of #374, awaiting release

**Closed by drewhoener** 2024-03-21 00:52 UTC
Labels: bug (visual), triage
