### ISSUE TITLE
[Bug]:  UI Suite error

### ISSUE THREAD

**Issue by drkanbs** [Annosz/UIInfoSuite2#623] opened 2024-11-06 01:09 UTC
### Mod Version

v2.3.5

### Multiplayer

Multiplayer (Host)

### SMAPI Log

https://smapi.io/log/019b6f2d9ef440e596d13b8a7fb9a9f9

### Description

It seems to happen once I choose to exit the game back to desktop.  However, it is happening in both single player and multiplayer.

Also what's not showing up as an error on the error log:

 Failed loading PDB for 'UIInfoSuite2.dll'. Technical details:
Mono.Cecil.Cil.SymbolsNotMatchingException: Symbols were found but are not matching the assembly
   at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader, Boolean throwIfSymbolsAreNotMaching)
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   at Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
   at StardewModdingAPI.Framework.ModLoading.AssemblyLoader.GetReferencedLocalAssemblies(FileInfo file, HashSet`1 visitedAssemblyNames, IAssemblyResolver assemblyResolver)+MoveNext() in /home/pathoschild/git/SMAPI/src/SMAPI/Framework/ModLoading/AssemblyLoader.cs:line 280

**Comment by drewhoener** [comment] 2024-11-07 16:50
Duplicate of #624

**Closed by drewhoener** 2024-11-07 16:50 UTC
Labels: triage, bug (other)
