### ISSUE TITLE
[Visual Bug]: Scarecrow range shows range misalignment

### ISSUE THREAD

**Issue by BoyAndDragon** [Annosz/UIInfoSuite2#405] opened 2024-03-21 01:51 UTC
### Game Version

v2.3.0-alpha-2

### Multiplayer

Single Player

### Visual Settings

user interface scale：100%     Zoom：100%

### Description

![图片1](https://github.com/Annosz/UIInfoSuite2/assets/164279868/83060b33-2347-4e9c-bf71-c469df6a93cc)

**Comment by drewhoener** [comment] 2024-03-21 02:02
Duplicate of #377
Fixed by #397

**Closed by drewhoener** 2024-03-21 02:02 UTC
Labels: bug (visual), triage
