### ISSUE TITLE
[Bug]: Community Center information on items not working 

### ISSUE THREAD

**Issue by laireankale** [Annosz/UIInfoSuite2#395] opened 2024-03-20 21:35 UTC
### Game Version

v2.3.0-alpha-2

### Multiplayer

Single Player

### Breaking Bug

Non-Breaking

### Visual Settings

UI Scale: 100%, Zoom: 100%

### Description

When I have my inventory open and hover over an item that I have not yet donated to the community center (but is part of a bundle) it does not tell me it is part of a bundle. I only see the infographic if I have an item in my hot-bar and hover over it there (inventory closed).

**Comment by drewhoener** [comment] 2024-03-20 21:37
Duplicate of #374

**Closed by drewhoener** 2024-03-20 21:37 UTC
Labels: bug, triage
