### ISSUE TITLE
[Bug]: Mouse cursor stuck to character while playing with a Controller

### ISSUE THREAD

**Issue by Mysuki-twitch** [Annosz/UIInfoSuite2#393] opened 2024-03-20 19:48 UTC
### Game Version

v2.3.0-alpha-2

### Multiplayer

Single Player

### Breaking Bug

Non-Breaking

### Visual Settings

UI Scale: 100%, Zoom: 100%

### Description

So, I play on PC using my Xbox One controller. The problem is: whenever I start walking, the mouse cursor gets hidden (normal) but it automatically gets stuck to my character's feet. So everytime I walk close to something, let's say my crops, it starts to show the crops names and how many days to grow.
If I move the mouse cursor to the edge of my screen, it jumps back to my character when I start walking again. It's kind of annoying because there's information on my screen every single time LOL Why can't I just see stuff IF I move the cursor with my right analog like it was supposed to do? I don't want it stuck to me character :(
![Captura de tela 2024-03-20 164333](https://github.com/Annosz/UIInfoSuite2/assets/73810751/833aa0c2-fa1c-4c84-bf65-75d417fef24c)

**Comment by drewhoener** [comment] 2024-03-21 03:45
Hi @Mysuki-twitch, this is actually intended behavior by the mod!
If you're on controller, and the cursor has faded out, the "detect region" defaults to the tile in front of your farmer.
Is it something that you'd want to see a toggled option for? I could maybe look into that in the future

**Comment by drewhoener** [comment] 2024-03-21 23:08
Closing in favor of #420

**Closed by drewhoener** 2024-03-21 23:08 UTC
Labels: bug (visual), triage
