### ISSUE TITLE
marlon's birthday icon

### ISSUE THREAD

**Issue by Hidenks** [Annosz/UIInfoSuite2#186] opened 2022-05-26 10:24 UTC
Marlon's birthday icon does not appear and is spamming error messages in the smapi console. (sorry for my bad English) 

![MarlonBirthday](https://user-images.githubusercontent.com/106311559/170469692-d402544b-7a59-48f5-a58c-02be6632182e.png)
![UiInfoSuite2Error](https://user-images.githubusercontent.com/106311559/170469697-2f5d3455-8caf-4180-a981-3aaf6d8135d7.png)

**Comment by Annosz** [comment] 2022-05-26 12:27
Hi! Did you download the latest version of the mod? It should be fixed in [2.2.4](https://github.com/Annosz/UIInfoSuite2/tree/2.2.4).

**Comment by Hidenks** [comment] 2022-05-26 19:35
> Hi! Did you download the latest version of the mod? It should be fixed in [2.2.4](https://github.com/Annosz/UIInfoSuite2/tree/2.2.4) (it was released 6 days ago, so fairly new changes).

Yes, I'm using the latest version.

**Comment by Mimir0** [comment] 2022-05-29 11:38
Does it work with save?

**Comment by Puffeeydii** [comment] 2022-05-30 10:57
I was experiencing the same issue, birthday icon won't appear.

**Comment by Hidenks** [comment] 2022-06-05 21:04
> Does it work with sve?

Yeah, it works with SVE. For me, only Marlon's birthday was a bug.

**Comment by Annosz** [comment] 2022-06-06 16:14
I was not able to reproduce this issue on my environment (Marlon's icon is displayed correctly for me), but I made some changes which hopefully can fix problems with the custom NPC birthdays. I've created a pre-release for [version 2.2.5](https://github.com/Annosz/UIInfoSuite2/releases/tag/2.2.5) of the mod where I hope it will work already. Feel free to check it out and report back if there is still a problem.

**Comment by Hidenks** [comment] 2022-06-06 16:29
> I was not able to reproduce this issue on my environment (Marlon's icon is displayed correctly for me), but I made some changes which hopefully can fix problems with the custom NPC birthdays. I've created a pre-release for [version 2.2.5](https://github.com/Annosz/UIInfoSuite2/releases/tag/2.2.5) of the mod where I hope it will work already. Feel free to check it out and report back if there is still a problem.

Unfortunately, I've already passed his birthday. But I can try to arrive on the day again to test :D

**Comment by Hidenks** [comment] 2022-06-07 03:01
> Hm, yeah, that's an issue I forgot :D
> 
> I attached a testing save I use, if you want, you can validate that the icon works with it (and of course the 2.2.5 version of the mod). If it's still broken, then most likely one of your mods conflicts with UIInfoSuite2 [teszt_246725931.zip](https://github.com/Annosz/UIInfoSuite2/files/8846066/teszt_246725931.zip)

Sure, I'll test it right now.

**Comment by Hidenks** [comment] 2022-06-07 03:09
> Hm, yeah, that's an issue I forgot :D
> 
> I attached a testing save I use, if you want, you can validate that the icon works with it (and of course the 2.2.5 version of the mod). If it's still broken, then most likely one of your mods conflicts with UIInfoSuite2 [teszt_246725931.zip](https://github.com/Annosz/UIInfoSuite2/files/8846066/teszt_246725931.zip)

Yeaaaah! It is fixed! Ty so much :D

**Comment by Annosz** [comment] 2022-06-07 06:38
Resolved with [https://github.com/Annosz/UIInfoSuite2/commit/1aa87cd7712227a8a0bb66bb419ea827f6fbca4d](https://github.com/Annosz/UIInfoSuite2/commit/1aa87cd7712227a8a0bb66bb419ea827f6fbca4d)

**Closed by Annosz** 2022-06-07 06:38 UTC
Labels: bug
