### ISSUE TITLE
[Visual Bug]: Screen shows a random part of the map when going into a new location

### ISSUE THREAD

**Issue by zelleous** [Annosz/UIInfoSuite2#618] opened 2024-10-29 13:59 UTC
### Mod Version

v2.3.5

### Multiplayer

Multiplayer (Non-Host)

### Visual Settings

UI Scale: 100%, Zoom: 75%

### SMAPI Log

https://smapi.io/log/7c80c7a9d6b543fc96af922a4d838e33

### Issue

https://github.com/user-attachments/assets/0e538402-756f-4d40-87e5-68517cf04f4c

### Steps to Reproduce
1. Go to a part in the map

**Comment by drewhoener** [comment] 2024-11-07 17:41
Hi @zelleous, this isn't a function of UI Info Suite, I can't reproduce it. Maybe it was fixed in an update to SDV with 1.6.12?

**Closed by drewhoener** 2024-11-07 17:41 UTC
Labels: bug (visual), triage
