### ISSUE TITLE
I think it shouldn't be like this?

### ISSUE THREAD

**Issue by perolaazul** [Annosz/UIInfoSuite2#380] opened 2024-03-20 04:27 UTC
![ad](https://github.com/Annosz/UIInfoSuite2/assets/164128296/c6b06a2c-5808-4dd8-a34d-eaf53cf0e586)
![aa a](https://github.com/Annosz/UIInfoSuite2/assets/164128296/88db5f78-8244-4cf1-97a6-1cb8432342a9)

(I'm writing this on Google Translate, ok?)

I don't know why these bugs are happening, if it was because I downloaded the wrong version (I downloaded it from here, obviously.) or if it's because I'm playing the latest update of the game that came out today

**Comment by drewhoener** [comment] 2024-03-20 04:46
@perolaazul Very interesting! Was the first picture taken with the screenshot button in the options menu? I've never seen this.

The other 2 images I'm already aware of, and should have fixes for in the next few days.
Thank you for reporting!

**Comment by KariArisu** [comment] 2024-03-20 06:05
If you hadn't figured it out, yeah it's from the screenshot button in-game. The same happens with a few other mods like NPC Map Locations' minimap.

**Comment by laszlostark** [comment] 2024-03-20 10:41
Can confirm that this happens with the ingame screenshot functionality with mod version Alpha-2 on game version 1.6.1

**Comment by drewhoener** [comment] 2024-03-20 23:09
Duplicate of #400

**Closed by drewhoener** 2024-03-20 23:09 UTC
Labels: bug (visual), 1.6 Compatibility
