### ISSUE TITLE
Fish bundles indication not shown

### ISSUE THREAD

**Issue by pipqr** [Annosz/UIInfoSuite2#373] opened 2024-03-19 20:48 UTC
I have not yet unlocked community center on my new save. I can see the red indicators for Construction and Spring Foraging, but cannot see any fish bundles. I'm not sure what other bundles are invisible, as I only have materials from those three.

**Comment by drewhoener** [comment] 2024-03-19 22:43
Hi @pipqr, thanks for the issue.
To clarify, the community center box doesn't show up at all on the side when hovering over fish?

**Comment by pipqr** [comment] 2024-03-19 22:48
@drewhoener they did not show up anywhere, not even behind the inventory as others are reporting. I have just unlocked the fish bundles and they now show, along with the spring crops that were also missing their labels.
I'm not sure if the issue is that they appeared before unlock at all, or the fact that some didn't.

**Comment by drewhoener** [comment] 2024-03-20 04:50
@pipqr, After double checking, I believe that the bundle banner will only be displayed if the Junimo Scroll containing it is physically in the community center.
This explains why Spring foraging & Construction are displayed (even before you can read the scroll, it's still physically in the room).  

I'm going to close this issue, because I believe it's working as intended. If you believe that the functionality should change, e.g. No bundles should show before unlocking the community center, or all bundles should be shown by default, please feel free to make another issue with a feature request.

**Closed by drewhoener** 2024-03-20 04:50 UTC
Labels: wontfix
