### ISSUE TITLE
[Visual Bug]: HUD icons duplicate after quitting to title and reloading a save

### ISSUE THREAD

**Issue by eastevenson** [Annosz/UIInfoSuite2#437] opened 2024-03-24 18:45 UTC
### Mod Version

v2.3.0

### Multiplayer

Single Player

### Visual Settings

UI Scale 1, Zoom Level 1

### SMAPI Log

https://smapi.io/log/36f5bd40f8154da89d2ce26f095f44df

### Issue
Icons that appear beneath the date/time/weather HUD (indicating things such as Traveling Cart in town, daily luck, tomorrow's weather, etc,) are duplicated when reloading a save. The icons extend in a single line outward to the left with a complete set of the current icons, followed by another complete set in the same order. Icons that are removed (such as Queen of Sauce icon after viewing her program) are removed from both sets. New icons added during gameplay are sometimes added to both sets and sometimes only a single time. Some amount of duplication persists through multiple in-game days, potentially only being resolved if the player Exits to Desktop or otherwise stops the game software entirely. On one occasion, the icons also continued to display on screen during an overnight event sequence, and they also appeared on screen during a Community Center animation sequence after completing a bundle and causing the final remaining books to appear in the office and boiler room. They otherwise did not appear any place/time they shouldn't.

### Steps to Reproduce
1. Launch game and Load a save file. Verify icons currently displayed in the HUD.
2. Bring up the Pause menu and navigate to the Exit tab. Select Exit to Title. From the Title Screen, press Load and select the same file as before. HUD icons now appear in duplicate.
3. Repeat Step 2. HUD icons now appear in triplicate.
4. From the Exit tab of the Pause menu, select Exit to Desktop, or otherwise exit the game entirely. Relaunch the software and Load the same save file as before. HUD icons are no longer duplicated.

![20240323194358_1](https://github.com/Annosz/UIInfoSuite2/assets/17774048/4ce13358-cb56-41c8-a7a3-4ebff7f3eafb)
![20240322042953_1](https://github.com/Annosz/UIInfoSuite2/assets/17774048/f181fc27-49cd-4745-a2e7-b29ab181aba0)
![20240322041257_1](https://github.com/Annosz/UIInfoSuite2/assets/17774048/55100c4f-8806-49ed-bb24-e4909ad2772b)
![20240322025209_1](https://github.com/Annosz/UIInfoSuite2/assets/17774048/0171ca5c-d98c-4993-9512-7b61698855da)
![20240322025224_1](https://github.com/Annosz/UIInfoSuite2/assets/17774048/c671e2a0-588f-4d71-9d0c-58c12c016ca6)

**Comment by drewhoener** [comment] 2024-03-24 20:40
Hi @eastevenson, this is a known issue that has been fixed in the upcoming v2.3.1 release. 

Duplicate of #381

**Closed** 2024-03-24 20:40 UTC
Labels: bug (visual), duplicate

**Comment by eastevenson** [comment] 2024-03-24 22:20
Ah, sorry for the redundancy! I'm realizing when I looked through the set of issues it was filtering to only show open issues so I missed the one y'all had already handled so quickly and closed!

**Comment by drewhoener** [comment] 2024-03-24 22:21
Not a problem, thanks for reporting!
